# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-type: 'all'
    versioning-strategy: 'increase'
    open-pull-requests-limit: 5
    groups:
      angular:
        patterns:
          - '@angular/*'
      angular-material:
        patterns:
          - '@angular/cdk'
          - '@angular/material'
          - '@angular/material-*'
      testing:
        patterns:
          - 'jasmine*'
          - 'karma*'
          - '@types/jasmine'
      eslint:
        patterns:
          - 'eslint'
          - 'angular-eslint'
          - 'typescript-eslint'
          - 'eslint-*'
      prettier:
        patterns:
          - 'prettier'
          - 'prettier-*'
    target-branch: 'main'
    commit-message:
      prefix: 'deps'
      prefix-development: 'deps-dev'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 5
    target-branch: 'main'
    commit-message:
      prefix: 'ci'
